### ISSUE TITLE
Example ByteArrayExample fails with QZ_FAIL exception

### ISSUE THREAD

**Issue by hector-cao** [intel/qat-java#20]
hello,

I tried to follow the README and run the example, I got this error:

ubuntu@corsair-741103:~/qat-java$ sudo java -cp .:./target/classes/ com.intel.qat.examples.ByteArrayExample
com.intel.qat.QatException: QZ_FAIL: Error occurred while decompressing data.
	at com.intel.qat.InternalJNI.decompressByteArray(Native Method)
	at com.intel.qat.QatZipper.decompress(QatZipper.java:532)
	at com.intel.qat.QatZipper.decompress(QatZipper.java:500)
	at com.intel.qat.examples.ByteArrayExample.main(ByteArrayExample.java:29)

Here is my QAT configuration :

```
NUMA_0	70:00.0	/sys/bus/pci/devices/0000:70:00.0	sym;asym  	up
	 VF: 70:00.1 - /dev/vfio/467
	 VF: 70:00.2 - /dev/vfio/468
	 VF: 70:00.3 - /dev/vfio/469
	 VF: 70:00.4 - /dev/vfio/470
	 VF: 70:00.5 - /dev/vfio/471
	 VF: 70:00.6 - /dev/vfio/472
	 VF: 70:00.7 - /dev/vfio/473
	 VF: 70:01.0 - /dev/vfio/474
	 VF: 70:01.1 - /dev/vfio/475
	 VF: 70:01.2 - /dev/vfio/476
	 VF: 70:01.3 - /dev/vfio/477
	 VF: 70:01.4 - /dev/vfio/478
	 VF: 70:01.5 - /dev/vfio/479
	 VF: 70:01.6 - /dev/vfio/480
	 VF: 70:01.7 - /dev/vfio/481
	 VF: 70:02.0 - /dev/vfio/482

NUMA_2	ed:00.0	/sys/bus/pci/devices/0000:ed:00.0	dc        	up
	 VF: ed:00.1 - /dev/vfio/483
	 VF: ed:00.2 - /dev/vfio/484
	 VF: ed:00.3 - /dev/vfio/485
	 VF: ed:00.4 - /dev/vfio/486
	 VF: ed:00.5 - /dev/vfio/487
	 VF: ed:00.6 - /dev/vfio/488
	 VF: ed:00.7 - /dev/vfio/489
	 VF: ed:01.0 - /dev/vfio/490
	 VF: ed:01.1 - /dev/vfio/491
	 VF: ed:01.2 - /dev/vfio/492
	 VF: ed:01.3 - /dev/vfio/493
	 VF: ed:01.4 - /dev/vfio/494
	 VF: ed:01.5 - /dev/vfio/495
	 VF: ed:01.6 - /dev/vfio/496
	 VF: ed:01.7 - /dev/vfio/497
	 VF: ed:02.0 - /dev/vfio/498
```

**Comment by mulugetam** [comment]
Resolved in version 2.0.0.
